[project]
name = "sample-agent-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-framework==1.0.0",
    "agent-framework-devui>=1.0.0b260311",
    "debugpy>=1.8.19",
    "fastmcp>=2.14.2",
    "ruff>=0.14.7",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["agent-framework/demo/src"]
testpaths = ["agent-framework/demo/tests"]
